#include "module.h"
#include "repo.h"

#include <QFile>
#include <QRegularExpression>
#include <QSaveFile>

namespace {

QString moduleText()
{
    QFile file(modulePath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    return QString::fromUtf8(file.readAll());
}

QString capture(const QString &pattern)
{
    const QRegularExpressionMatch match = QRegularExpression(pattern).match(moduleText());
    return match.hasMatch() ? match.captured(1) : QString();
}

QString escape(const QString &value)
{
    QString out = value;
    out.replace('\\', "\\\\");
    out.replace('"', "\\\"");
    return out;
}

} // namespace

QString modulePath()
{
    return repoPath() + "/modules/user/git.nix";
}

QString moduleName()
{
    return capture(R"rx(\bname\s*=\s*"([^"]*)")rx");
}

QString moduleEmail()
{
    return capture(R"rx(\bemail\s*=\s*"([^"]*)")rx");
}

QString moduleHost()
{
    return capture(R"rx("([^"]+)"\s*=\s*\{\s*IdentityFile)rx");
}

QString moduleKey()
{
    return capture(R"rx(IdentityFile\s*=\s*"~/\.ssh/([^"]+)")rx");
}

QString writeModule(const QString &name, const QString &email, const QString &host,
                    const QString &key)
{
    const QString text = QString(R"(# Auto-generated by nixlycc — Control Panel → Git.
{ pkgs, ... }:

{

    home.packages = with pkgs; [
        libsecret
        git-lfs
    ];

    programs.git = {
        enable = true;
        package = pkgs.gitFull;
        signing.format = null;
        settings.user = {
            name = "%1";
            email = "%2";
        };
    };

    programs.ssh = {
        enable = true;
        enableDefaultConfig = false;
        settings = {
          "*" = {
            Compression = true;
          };
          "%3" = {
            IdentityFile = "~/.ssh/%4";
          };
        };
    };
}
)")
                            .arg(escape(name), escape(email), escape(host), escape(key));

    QSaveFile file(modulePath());
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return QString("Could not write %1").arg(modulePath());
    file.write(text.toUtf8());
    if (!file.commit())
        return QString("Could not write %1").arg(modulePath());
    return QString();
}
