#include "repo.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QProcessEnvironment>
#include <QSaveFile>
#include <QTextStream>

namespace {

QString confPath()
{
    return QDir::homePath() + "/.local/nixlyos/git.conf";
}

/* Runs git in dir. Returns the exit code; output lands in out. Anything that
 * would ask a human — a password prompt, an unknown host key — must fail
 * instead, since there is no terminal attached. */
int git(const QStringList &args, const QString &dir, QString *out)
{
    QProcess proc;
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    env.insert("GIT_TERMINAL_PROMPT", "0");
    env.insert("GIT_SSH_COMMAND", "ssh -o BatchMode=yes");
    proc.setProcessEnvironment(env);
    proc.setWorkingDirectory(dir);
    proc.setProcessChannelMode(QProcess::MergedChannels);
    proc.start("git", args);
    if (!proc.waitForFinished(120000)) {
        if (out)
            *out = "git timed out";
        return -1;
    }
    if (out)
        *out = QString::fromUtf8(proc.readAll()).trimmed();
    return proc.exitCode();
}

} // namespace

QString repoPath()
{
    return QDir::homePath() + "/.nixlyos";
}

QString repoRemote()
{
    QString out;
    if (git({ "remote", "get-url", "origin" }, repoPath(), &out) != 0)
        return QString();
    return out;
}

QString gitConfigValue(const QString &key)
{
    QString out;
    if (git({ "config", "--get", key }, QDir::homePath(), &out) != 0)
        return QString();
    return out;
}

QString createRepo(const QString &url, const QString &name, const QString &email)
{
    const QString dir = repoPath();
    if (!QDir().mkpath(dir))
        return QString("Could not create %1").arg(dir);

    QString out;
    if (!QFileInfo::exists(dir + "/.git") && git({ "init", "-b", "main" }, dir, &out) != 0)
        return out;

    if (git({ "config", "user.name", name }, dir, &out) != 0)
        return out;
    if (git({ "config", "user.email", email }, dir, &out) != 0)
        return out;

    const bool hasRemote = git({ "remote", "get-url", "origin" }, dir, nullptr) == 0;
    if (git({ "remote", hasRemote ? "set-url" : "add", "origin", url }, dir, &out) != 0)
        return out;

    if (git({ "add", "-A" }, dir, &out) != 0)
        return out;
    if (git({ "diff", "--cached", "--quiet" }, dir, nullptr) != 0
        && git({ "commit", "-m", "nixlyOS config" }, dir, &out) != 0)
        return out;

    if (git({ "push", "-u", "origin", "HEAD" }, dir, &out) != 0)
        return out;
    return QString();
}

bool autoCommitEnabled()
{
    QFile file(confPath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return false;
    QTextStream in(&file);
    while (!in.atEnd()) {
        if (in.readLine().trimmed() == "autocommit=1")
            return true;
    }
    return false;
}

QString setAutoCommit(bool enabled)
{
    const QString path = confPath();
    QDir().mkpath(QFileInfo(path).absolutePath());

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return QString("Could not write %1").arg(path);
    QTextStream out(&file);
    out << "# Auto-generated by nixlycc\n";
    out << "autocommit=" << (enabled ? 1 : 0) << "\n";
    if (!file.commit())
        return QString("Could not write %1").arg(path);
    return QString();
}
