#include "pkglist.h"

#include <QDir>
#include <QFile>
#include <QRegularExpression>
#include <QSaveFile>
#include <algorithm>

namespace {

QString readFile(const QString &path)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString();
    return QString::fromUtf8(file.readAll());
}

/* Attribute names inside `with <scope>; [ … ]`, comments dropped. */
QStringList listFor(const QString &text, const QString &scope)
{
    const QRegularExpression head(QString(R"(\bwith\s+%1;\s*\[)").arg(QRegularExpression::escape(scope)));
    const QRegularExpressionMatch match = head.match(text);
    if (!match.hasMatch())
        return QStringList();

    const int open = match.capturedEnd() - 1;
    int depth = 0, close = -1;
    for (int i = open; i < text.size() && close < 0; ++i) {
        if (text[i] == '[')
            ++depth;
        else if (text[i] == ']' && --depth == 0)
            close = i;
    }
    if (close < 0)
        return QStringList();

    QString body;
    for (const QString &line : text.mid(open + 1, close - open - 1).split('\n')) {
        const int hash = line.indexOf('#');
        body += (hash < 0 ? line : line.left(hash)) + '\n';
    }

    static const QRegularExpression space(R"(\s+)");
    return body.split(space, Qt::SkipEmptyParts);
}

} // namespace

QString packagesPath()
{
    return QDir::homePath() + "/.nixlyos/modules/core/packages.nix";
}

QList<PkgEntry> installedPackages()
{
    const QString text = readFile(packagesPath());
    QList<PkgEntry> entries;
    for (const QString &attr : listFor(text, "pkgs"))
        entries.append({ attr, false });
    for (const QString &attr : listFor(text, "pkgs-unstable"))
        entries.append({ attr, true });
    return entries;
}

/* The whole file is regenerated: the two lists have to stay in step with each
 * other, and packages.nix holds nothing else. pkgs-unstable is the
 * nixos-unstable input flake.nix already passes to home-manager. */
QString writeInstalledPackages(const QList<PkgEntry> &entries)
{
    QStringList stable, unstable;
    for (const PkgEntry &e : entries)
        (e.unstable ? unstable : stable) << e.attr;
    for (QStringList *list : { &stable, &unstable }) {
        list->removeDuplicates();
        list->sort(Qt::CaseInsensitive);
    }

    QString text = "# Auto-generated by nixlycc — Control Panel → Applications.\n"
                   "{ ... }:\n"
                   "\n"
                   "{\n"
                   "  config.home-manager.sharedModules = [\n"
                   "    ({ pkgs, pkgs-unstable, ... }: {\n"
                   "      home.packages = (with pkgs; [\n";
    for (const QString &attr : stable)
        text += "        " + attr + "\n";
    text += "      ]) ++ (with pkgs-unstable; [\n";
    for (const QString &attr : unstable)
        text += "        " + attr + "\n";
    text += "      ]);\n"
            "    })\n"
            "  ];\n"
            "}\n";

    const QString path = packagesPath();
    QDir().mkpath(QFileInfo(path).absolutePath());
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return QString("Could not write %1").arg(path);
    file.write(text.toUtf8());
    if (!file.commit())
        return QString("Could not write %1").arg(path);
    return QString();
}
