#include "conf.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QTextStream>

namespace {

const QString kTalkBind = "ptt-bind=";
const QString kTalkLabel = "ptt-label=";
const QString kMuteBind = "ptm-bind=";
const QString kMuteLabel = "ptm-label=";

void writeBind(QTextStream &out, const Bind &bind, const QString &key, const QString &labelKey)
{
    out << key << bind.value << "\n" << labelKey << bind.label << "\n";
}

} // namespace

QString gamingConfPath()
{
    return QDir::homePath() + "/.local/nixlyos/gaming.conf";
}

/* Each ptm-label follows its ptm-bind. */
GamingConf loadGamingConf()
{
    GamingConf conf;
    QFile file(gamingConfPath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return conf;

    while (!file.atEnd()) {
        const QString line = QString::fromUtf8(file.readLine()).trimmed();
        if (line.startsWith(kTalkBind))
            conf.talk.value = line.mid(kTalkBind.size());
        else if (line.startsWith(kTalkLabel))
            conf.talk.label = line.mid(kTalkLabel.size());
        else if (line.startsWith(kMuteBind))
            conf.voipMute.append({line.mid(kMuteBind.size()), QString()});
        else if (line.startsWith(kMuteLabel) && !conf.voipMute.isEmpty())
            conf.voipMute.last().label = line.mid(kMuteLabel.size());
    }
    return conf;
}

/* Atomic rename, so nixlytile never reads half a file. */
bool saveGamingConf(const GamingConf &conf)
{
    const QString path = gamingConfPath();
    QDir().mkpath(QFileInfo(path).absolutePath());

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;

    QTextStream out(&file);
    out << "# Auto-generated by nixlycc gaming page\n";
    if (!conf.talk.value.isEmpty())
        writeBind(out, conf.talk, kTalkBind, kTalkLabel);
    for (const Bind &bind : conf.voipMute)
        writeBind(out, bind, kMuteBind, kMuteLabel);
    out.flush();
    return file.commit();
}
