#include "conf.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QTextStream>

namespace {

const QString kTalkBind = "ptt-bind=";
const QString kTalkLabel = "ptt-label=";
const QString kMuteBind = "ptm-bind=";
const QString kMuteLabel = "ptm-label=";
const QString kDynamicRender = "dynamic-render=";

using Apply = void (*)(GamingConf &, const QString &);

/* Each ptm-label follows its ptm-bind. */
const struct {
    const QString &key;
    Apply apply;
} kKeys[] = {
    { kTalkBind, [](GamingConf &c, const QString &v) { c.talk.value = v; } },
    { kTalkLabel, [](GamingConf &c, const QString &v) { c.talk.label = v; } },
    { kMuteBind, [](GamingConf &c, const QString &v) { c.voipMute.append({v, QString()}); } },
    { kMuteLabel, [](GamingConf &c, const QString &v) {
        if (!c.voipMute.isEmpty())
            c.voipMute.last().label = v;
    } },
    { kDynamicRender, [](GamingConf &c, const QString &v) { c.dynamicRender = v != "0"; } },
};

void applyLine(GamingConf &conf, const QString &line)
{
    for (const auto &k : kKeys) {
        if (!line.startsWith(k.key))
            continue;
        k.apply(conf, line.mid(k.key.size()));
        return;
    }
}

void writeBind(QTextStream &out, const Bind &bind, const QString &key, const QString &labelKey)
{
    out << key << bind.value << "\n" << labelKey << bind.label << "\n";
}

} // namespace

QString gamingConfPath()
{
    return QDir::homePath() + "/.local/nixlyos/gaming.conf";
}

GamingConf loadGamingConf()
{
    GamingConf conf;
    QFile file(gamingConfPath());
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return conf;

    while (!file.atEnd())
        applyLine(conf, QString::fromUtf8(file.readLine()).trimmed());
    return conf;
}

/* Atomic rename, so nixlytile never reads half a file. */
bool saveGamingConf(const GamingConf &conf)
{
    const QString path = gamingConfPath();
    QDir().mkpath(QFileInfo(path).absolutePath());

    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;

    QTextStream out(&file);
    out << "# Auto-generated by nixlycc gaming page\n";
    if (!conf.talk.value.isEmpty())
        writeBind(out, conf.talk, kTalkBind, kTalkLabel);
    for (const Bind &bind : conf.voipMute)
        writeBind(out, bind, kMuteBind, kMuteLabel);
    out << kDynamicRender << (conf.dynamicRender ? "1" : "0") << "\n";
    out.flush();
    return file.commit();
}
