#include "module.h"
#include "../git/repo.h"
#include "settings.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>

namespace {

QString nixString(const QString &value)
{
    QString out = value;
    out.replace('\\', "\\\\");
    out.replace('"', "\\\"");
    return "\"" + out + "\"";
}

QString nixBool(bool value)
{
    return value ? "true" : "false";
}

/* A keyd [main] block: "  capslock = esc;" per binding, sorted so the file
 * does not churn. */
QString keydSection(const QHash<int, QString> &bindings, bool mouse)
{
    QStringList lines;
    for (auto it = bindings.constBegin(); it != bindings.constEnd(); ++it) {
        if (it.value().isEmpty())
            continue;
        const QString name = mouse ? keydButtonName(it.key()) : keydKeyName(it.key());
        if (name.isEmpty())
            continue;
        lines << QString("            %1 = %2;").arg(name, nixString(it.value()));
    }
    lines.sort();
    return lines.join('\n');
}

QString hardwareScript(const InputSettings &settings)
{
    QStringList lines;
    if (settings.mouse.dpi > 0)
        lines << QString("      ratbagctl \"%1\" dpi set %2 || true")
                     .arg(settings.mouse.device)
                     .arg(settings.mouse.dpi);
    if (settings.mouse.pollingRate > 0)
        lines << QString("      ratbagctl \"%1\" rate set %2 || true")
                     .arg(settings.mouse.device)
                     .arg(settings.mouse.pollingRate);

    const KeyboardSettings &kb = settings.keyboard;
    if (kb.rgbMode != "off") {
        const QString colour = QString(kb.rgbColor).remove('#');
        lines << QString("      openrgb --noautoconnect --mode %1 --color %2 --brightness %3 "
                         "|| true")
                     .arg(kb.rgbMode, colour)
                     .arg(kb.brightness);
    }
    return lines.join('\n');
}

} // namespace

QString inputModulePath()
{
    return QDir::homePath() + "/.nixlyos/modules/core/input.nix";
}

namespace {

/* modules/core/default.nix lists its imports one by one, so a brand new
 * module has to be added there or nothing evaluates it. */
QString ensureImported()
{
    const QString path = QDir::homePath() + "/.nixlyos/modules/core/default.nix";
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return QString("Could not read %1").arg(path);
    QString text = QString::fromUtf8(file.readAll());
    file.close();

    if (text.contains("./input.nix"))
        return QString();

    const int at = text.indexOf("imports = [");
    if (at < 0)
        return QString("No imports list in %1").arg(path);
    const int eol = text.indexOf('\n', at);
    if (eol < 0)
        return QString("No imports list in %1").arg(path);
    text.insert(eol + 1, "    ./input.nix\n");

    QSaveFile out(path);
    if (!out.open(QIODevice::WriteOnly | QIODevice::Text))
        return QString("Could not write %1").arg(path);
    out.write(text.toUtf8());
    if (!out.commit())
        return QString("Could not write %1").arg(path);
    return QString();
}

} // namespace

QString writeInputModule(const InputSettings &settings)
{
    const MouseSettings &mouse = settings.mouse;
    const KeyboardSettings &kb = settings.keyboard;

    const QString mouseBindings = keydSection(mouse.actions, true);
    const QString keyBindings = keydSection(kb.remaps, false);
    const QString hardware = hardwareScript(settings);
    const bool wantsRatbag = mouse.dpi > 0 || mouse.pollingRate > 0;
    const bool wantsRgb = kb.rgbMode != "off";

    QString text =
        "# Auto-generated by nixlycc — Control Panel → Mouse & Keyboard.\n"
        "{ lib, pkgs, ... }:\n"
        "\n"
        "{\n";

    /* timezone_locale.nix already sets a layout; this page is the newer word
     * on it, so it has to win. */
    text += QString("  services.xserver.xkb.layout = lib.mkForce %1;\n").arg(nixString(kb.layout));
    text += QString("  services.xserver.xkb.variant = lib.mkForce %1;\n").arg(nixString(kb.variant));
    /* The console keymap is set by name, not derived from xkb — deriving it
     * would collide with the keyMap another module already defines. */
    text += QString("  console.keyMap = lib.mkForce %1;\n\n")
                .arg(nixString(kb.layout == "gb" ? "uk" : kb.layout));

    text += "  # Read by nixlytile, which re-applies it to every pointer and keyboard as\n"
            "  # soon as the file changes — a switch takes effect without logging out.\n"
            "  environment.etc.\"nixlyos/input.conf\".text = ''\n";
    text += QString("    accel-profile=%1\n").arg(mouse.accelProfile);
    text += QString("    accel-speed=%1\n").arg(mouse.accelSpeed, 0, 'f', 2);
    text += QString("    natural-scroll=%1\n").arg(nixBool(mouse.naturalScroll));
    text += QString("    left-handed=%1\n").arg(nixBool(mouse.leftHanded));
    text += QString("    middle-button-emulation=%1\n").arg(nixBool(mouse.middleEmulation));
    text += QString("    scroll-method=%1\n").arg(mouse.scrollMethod);
    text += QString("    button-map=%1\n").arg(mouse.buttonMap);
    text += QString("    keyboard-layout=%1\n").arg(kb.layout);
    text += QString("    keyboard-variant=%1\n").arg(kb.variant);
    text += QString("    repeat-delay=%1\n").arg(kb.repeatDelay);
    text += QString("    repeat-rate=%1\n").arg(kb.repeatRate);
    text += "  '';\n";

    if (!mouseBindings.isEmpty() || !keyBindings.isEmpty()) {
        text += "\n  services.keyd = {\n    enable = true;\n    keyboards = {\n";
        if (!keyBindings.isEmpty()) {
            text += "      keyboard = {\n";
            text += QString("        ids = [ %1 ];\n")
                        .arg(kb.id.isEmpty() ? "\"*\"" : nixString(kb.id));
            text += "        settings.main = {\n" + keyBindings + "\n        };\n      };\n";
        }
        if (!mouseBindings.isEmpty()) {
            /* keyd calls mouse support experimental, so the mouse is listed by
             * id only — never through the wildcard. */
            text += "      mouse = {\n";
            text += QString("        ids = [ %1 ];\n").arg(nixString(mouse.id));
            text += "        settings.main = {\n" + mouseBindings + "\n        };\n      };\n";
        }
        text += "    };\n  };\n";
    }

    if (wantsRatbag)
        text += "\n  services.ratbagd.enable = true;\n";
    if (wantsRgb)
        text += "  services.hardware.openrgb.enable = true;\n";

    if (!hardware.isEmpty()) {
        text += "\n  systemd.services.nixly-input-hardware = {\n"
                "    description = \"Apply nixlycc mouse and keyboard hardware settings\";\n"
                "    wantedBy = [ \"multi-user.target\" ];\n";
        QStringList after;
        if (wantsRatbag)
            after << "\"ratbagd.service\"";
        if (wantsRgb)
            after << "\"openrgb.service\"";
        text += QString("    after = [ %1 ];\n").arg(after.join(' '));
        text += QString("    path = with pkgs; [ %1 ];\n")
                    .arg(QString(wantsRatbag ? "libratbag " : "") + (wantsRgb ? "openrgb" : ""));
        text += "    serviceConfig.Type = \"oneshot\";\n"
                "    script = ''\n";
        text += hardware + "\n";
        text += "    '';\n  };\n";
    }

    text += "}\n";

    const QString path = inputModulePath();
    QDir().mkpath(QFileInfo(path).absolutePath());
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return QString("Could not write %1").arg(path);
    file.write(text.toUtf8());
    if (!file.commit())
        return QString("Could not write %1").arg(path);

    const QString importError = ensureImported();
    if (!importError.isEmpty())
        return importError;

    /* A flake built from a dirty tree ignores untracked files, so the brand
     * new module has to enter the index before the rebuild can see it. */
    return stageFile(path);
}
